"""High-level reusable workflow helpers for notebook-facing experiments."""

from ._core import (
    build_system,
    edge_table,
    exact_observables_summary,
    format_tfim_5x5_vmc_performance_report,
    half_subsystem,
    history_table,
    initialize_random_parameters,
    parameter_table,
    renyi2_subsystem_scan_summary,
    run_architecture_benchmark,
    run_architecture_comparison,
    run_architecture_disorder_comparison,
    run_random_architecture_study,
    run_architecture_sweep,
    run_incremental_exercise_1_ed_benchmark,
    run_ghz_bonus_workflow,
    run_hamiltonian_system_size_sweep,
    run_non_ed_vmc_benchmark,
    run_tfim_5x5_vmc_performance_benchmark,
    run_vmc_experiment,
    sampler_acceptance_diagnostics,
    sampled_entropy_scaling_summary,
    tfim_config,
    tfim_proxy_sweep_points,
)

__all__ = [
    "build_system",
    "edge_table",
    "exact_observables_summary",
    "format_tfim_5x5_vmc_performance_report",
    "half_subsystem",
    "history_table",
    "initialize_random_parameters",
    "parameter_table",
    "renyi2_subsystem_scan_summary",
    "run_architecture_benchmark",
    "run_architecture_comparison",
    "run_architecture_disorder_comparison",
    "run_random_architecture_study",
    "run_architecture_sweep",
    "run_incremental_exercise_1_ed_benchmark",
    "run_ghz_bonus_workflow",
    "run_hamiltonian_system_size_sweep",
    "run_non_ed_vmc_benchmark",
    "run_tfim_5x5_vmc_performance_benchmark",
    "run_vmc_experiment",
    "sampler_acceptance_diagnostics",
    "sampled_entropy_scaling_summary",
    "tfim_config",
    "tfim_proxy_sweep_points",
]
